# This is a basic workflow to help you get started with Actions

name: Grid Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: ['master', 'grid/**']
  pull_request:
    branches: ['master', 'grid/**']
    paths:
      - '.github/workflows/grid-test.yml'
      - 'css/grid*'
      - 'samples/grid-lite/**'
      - 'samples/grid-pro/**'
      - 'test/cypress/grid/visual/**'
      - 'test/cypress/grid/integration/**'
      - 'ts/Data/**'
      - 'ts/Grid/**'

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  grid_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: highcharts

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: highcharts/package-lock.json

      - name: Install Dependencies
        run: |
          cd highcharts
          npm ci

      - name: Build Highcharts
        run: |
          cd highcharts
          npx gulp scripts

      - name: Build Dashboards
        run: |
          cd highcharts
          npx gulp scripts --product Dashboards

      - name: Run Grid Tests
        run: |
          cd highcharts
          npx gulp test --product Grid

      - name: Checkout utils
        uses: actions/checkout@v4
        with:
          repository: highcharts/highcharts-utils
          path: utils
          fetch-depth: 1

      - name: Install Highcharts Utils
        run: |
          cd utils
          npm ci

      - name: Run Grid Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: node ../utils/server --localOnly
          wait-on: 'http://localhost:3031/grid/grid-lite.js http://localhost:3031/grid/grid-pro.js'
          browser: chrome
          working-directory: highcharts
          config-file: test/cypress/grid/config.mjs
          install: false
