name: Highcharts headless tests

on:
  workflow_call:
    inputs:
      testTimezones:
        description: 'Whether timezone tests should run'
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      testTimezones:
        description: 'Whether timezone tests should run'
        required: false
        default: false
        type: boolean

jobs:
  test_unit_tests:
    name: Node unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Highcharts
        run: npx gulp scripts

      - name: Run unit tests
        run: npm run test-node

  test_cypress:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: highcharts

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: highcharts/package-lock.json

      - name: Install Highcharts deps
        run: |
          cd highcharts
          npm ci

      - name: Build Highcharts
        run: |
          cd highcharts
          npx gulp scripts

      - name: Checkout utils
        uses: actions/checkout@v4
        with:
          repository: highcharts/highcharts-utils
          path: utils
          fetch-depth: 1

      - name: Install Highcharts Utils
        run: |
          cd utils
          npm ci

      - name: Run Cypress test
        uses: cypress-io/github-action@v6
        with:
          start: node ../utils/server --localOnly
          wait-on: 'http://localhost:3031/highcharts.js'
          browser: chrome
          working-directory: highcharts
          config-file: test/cypress/highcharts/config.mjs
          install: false

  ### HEADLESS LINUX ###
  test_headless:
    name: Test with headless browsers
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      ### SETUP ###
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - uses: browser-actions/setup-chrome@v2
        id: setup-chrome
        with:
          install-chromedriver: true

      - run: |
          export CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}
          echo $CHROME_BIN
          $CHROME_BIN --version

      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest-esr
      - uses: browser-actions/setup-geckodriver@latest
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Display
        run: |
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Install Dependencies
        run: npm ci
      ### TASKS ###
      - name: Build Highcharts
        run: npx gulp scripts

      - name: Run Tests (Chrome)
        run: |
          export DISPLAY=:99
          npx gulp test --single-run --ts --splitbrowsers ChromeHeadless
      - name: Output logged errors
        run: cat ./test/console.log
      - name: Check Firefox
        run: |
          firefox --version
          whereis firefox
      - name: Run Tests (Firefox)
        run: |
          export DISPLAY=:99
          npx gulp test --single-run --splitbrowsers Firefox --force
      - name: Output logged errors
        run: cat ./test/console.log
      - name: Run timezone tests
        if: ${{ inputs.testTimezones }}
        run: |
          ./.github/scripts/test_timezones.sh -b=ChromeHeadless

  # ### HEADLESS MACOS ###
  # test_macos:
  #   name: Test with MacOS
  #   timeout-minutes: 10
  #   runs-on: macos-latest
  #   steps:
  #     ### SETUP ###
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 'lts/*'
  #         cache: 'npm'
  #     - name: Install Dependencies
  #       run: npm i
  #     ### TASKS ###
  #     - name: Build Highcharts
  #       run: npx gulp scripts
  #     - name: Run Tests (Safari)
  #       run: npx gulp test --single-run --splitbrowsers Safari
