name: Highcharts headless tests

on:
  workflow_call:
    inputs:
      testTimezones:
        description: 'Whether timezone tests should run'
        required: false
        default: false
        type: boolean

jobs:
  test_unit_tests:
    name: Node unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Run unit tests
        run: npx ts-node test/ts-node-unit-tests/index.ts

  test_cypress:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          browser: chrome

      - name: Build Highcharts
        run: npx gulp scripts

      - name: Install utils
        run: npm i github:highcharts/highcharts-utils

      - name: Run Cypress test
        uses: cypress-io/github-action@v6
        with:
          start: npx cross-env NODE_PATH=${GITHUB_WORKSPACE}/node_modules node node_modules/@highcharts/highcharts-utils/server --localOnly
          wait-on: 'http://localhost:3031/highcharts.js'
          browser: chrome
          install: false

  ### HEADLESS LINUX ###
  test_headless:
    name: Test with headless browsers
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      ### SETUP ###
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - uses: nanasess/setup-chromedriver@v2
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest-esr
      - uses: browser-actions/setup-geckodriver@latest
      - name: Setup Display
        run: |
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Install Dependencies
        run: npm i
      ### TASKS ###
      - name: Build Highcharts
        run: npx gulp scripts
      - name: Check Chrome
        run: |
          chrome --version
          whereis chrome
      - name: Run Tests (Chrome)
        run: |
          export DISPLAY=:99
          npx gulp test --single-run --splitbrowsers Chrome
      - name: Check Firefox
        run: |
          firefox --version
          whereis firefox
      - name: Run Tests (Firefox)
        run: |
          export DISPLAY=:99
          npx gulp test --single-run --splitbrowsers Firefox

      - name: Run timezone tests
        if: ${{ inputs.testTimezones }}
        run: |
          ./.github/scripts/test_timezones.sh -b=ChromeHeadless

  # ### HEADLESS MACOS ###
  # test_macos:
  #   name: Test with MacOS
  #   timeout-minutes: 10
  #   runs-on: macos-latest
  #   steps:
  #     ### SETUP ###
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: lts/*
  #         cache: 'npm'
  #     - name: Install Dependencies
  #       run: npm i
  #     ### TASKS ###
  #     - name: Build Highcharts
  #       run: npx gulp scripts
  #     - name: Run Tests (Safari)
  #       run: npx gulp test --single-run --splitbrowsers Safari
