name: Playwright Browserstack Tests
on:
  workflow_dispatch
jobs:
  test_playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: browserstack
    name: Playwright
    
    steps:
    - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_KEY }}
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        npm i
        npm i https://github.com/browserstack/node-js-playwright-browserstack.git

    - name: Build Highcharts
      run: npx gulp scripts

    - name: Checkout utils
      uses: actions/checkout@v4
      with:
        repository: highcharts/highcharts-utils
        path: utils
        fetch-depth: 1

    - name: Install Highcharts Utils
      run: |
        cd utils
        npm i

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Update Chrome
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt update
        sudo apt --only-upgrade install google-chrome-stable
    - name: Chrome info
      run: |
        set CHROME_BIN $(which chrome || which google-chrome || which chromium)
        echo $CHROME_BIN
        $CHROME_BIN --version
    - uses: nanasess/setup-chromedriver@v2
    - uses: browser-actions/setup-firefox@latest
      with:
        firefox-version: latest-esr
    - uses: browser-actions/setup-geckodriver@latest
    - name: Setup Display
      run: |
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: 'BrowserStackLocal Setup'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: start
        local-identifier: 'playwright-highcharts'
    - name: Run Playwright tests
      env: 
        BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      run: |
        export DISPLAY=:99
        npx browserstack-node-sdk playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: 'BrowserStackLocal Stop'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: stop
