name: Test tooling

on:
  pull_request:
    branches: [
      'master',
      'tools/*'
    ]
    paths:
      - 'package.json'
      - 'tools/**/*'
      - '.github/workflows/test-tooling.yml'
      - 'tests/internal/*'
  workflow_dispatch:

permissions:
   contents: read

jobs:
  notify:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ['lts/*', 'latest']

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run test
        run: node --test "./tools/gulptasks-tests/*.mjs"

